MetadataFilePath: clean_beta_metadata/cleanMetadataWithDescriptionsAndAnnotationsbeta.xml

EntityTypes:
  - Name: microsoft.graph.group
    RootUri: /groups
    Upsertable: true
    IgnoredProperties:
      - accessType
      - allowExternalSenders
      - assignedLabels
      - assignedLicenses
      - autoSubscribeNewMembers
      - hasMembersWithLicenseErrors
      - hideFromAddressLists
      - hideFromOutlookClients
      - isArchived
      - isFavorite
      - isSubscribedByMail
      - licenseProcessingState
      - membershipRuleProcessingStatus
      - unseenConversationsCount
      - unseenCount
      - unseenMessagesCount
    NavigationProperty:
      - members
      - owners
    RequiredOnWrite:
      - displayName
      - mailEnabled
      - mailNickname
      - securityEnabled
      - uniqueName
    ReadOnly:
      - createdByAppId
      - createdDateTime
      - expirationDateTime
      - isManagementRestricted
      - mail
      - onPremisesDomainName
      - onPremisesLastSyncDateTime
      - onPremisesNetBiosName
      - onPremisesProvisioningErrors
      - onPremisesSamAccountName
      - onPremisesSecurityIdentifier
      - onPremisesSyncEnabled
      - proxyAddresses
      - renewedDateTime
      - securityIdentifier
  - Name: microsoft.graph.application
    RootUri: /applications
    Upsertable: true
    IgnoredProperties:
      - onPremisesPublishing
      - oauth2RequirePostResponse
    RequiredOnWrite:
      - displayName
      - uniqueName
    ReadOnly:
      - appId
      - certification
      - createdDateTime
      - publisherDomain
  - Name: microsoft.graph.servicePrincipal
    RootUri: /servicePrincipals
    Upsertable: true
    IgnoredProperties:
      - customSecurityAttributes
      - errorUrl
      - passwordSingleSignOnSettings
    RequiredOnWrite:
      - appId
    ReadOnly:
      - applicationTemplateId
      - appOwnerOrganizationId
      - signInAudience
  - Name: microsoft.graph.federatedIdentityCredential
    RootUri: /applications/federatedIdentityCredentials
    Upsertable: true
    ContainerEntitySet: applications
    RequiredOnWrite:
      - audiences
      - issuer
      - name
      - subject
  - Name: microsoft.graph.oAuth2PermissionGrant
    RootUri: /oauth2PermissionGrants
    Upsertable: false
    Updatable: true
    IgnoredProperties:
      - expiryTime
      - startTime
    RequiredOnWrite:
      - clientId
      - consentType
      - resourceId
    FilterProperty:
      - clientId
      - consentType
      - resourceId
    CompositeKey:
      - clientId
      - consentType
      - resourceId
  - Name: microsoft.graph.appRoleAssignment
    RootUri: /appRoleAssignedTo
    Upsertable: false
    Updatable: false
    ContainerEntitySet: servicePrincipals
    ContainerKeyProperty: resourceId
    RequiredOnWrite:
      - appRoleId
      - principalId
      - resourceId
    ReadOnly:
      - creationTimestamp
      - principalDisplayName
      - principalType
    CompositeKey:
      - appRoleId
      - principalId
  - Name: microsoft.graph.appRole
    ReadOnly:
      - origin
  - Name: microsoft.graph.informationalUrl
    ReadOnly:
      - logoUrl
  - Name: microsoft.graph.passwordCredential
    IgnoredProperties:
      - customKeyIdentifier
    ReadOnly:
      - hint
      - secretText
  - Name: microsoft.graph.windowsApplication
    ReadOnly:
      - packageSid
  - Name: microsoft.graph.permissionScope
    IgnoredProperties:
      - origin
  - Name: microsoft.graph.directoryObject
    ReadOnly:
      - deletedDateTime
  - Name: microsoft.graph.entity
    ReadOnly:
      - id
  - Name: microsoft.graph.subscription
    RootUri: /subscriptions
    AvailableProperty:
      - applicationId
      - changeType
      - clientState
      - creatorId
      - encryptionCertificate
      - encryptionCertificateId
      - expirationDateTime
      - includeResourceData
      - latestSupportedTlsVersion
      - lifecycleNotificationUrl
      - notificationContentType
      - notificationQueryOptions
      - notificationUrl
      - notificationUrlAppId
      - resource
    RequiredOnWrite:
      - changeType
      - expirationDateTime
      - notificationUrl
      - resource
    ReadOnly:
      - applicationId
      - creatorId