MetadataFilePath: clean_v10_metadata/cleanMetadataWithDescriptionsAndAnnotationsv1.0.xml

EntityTypes:
  - Name: microsoft.graph.group
    RootUri: /groups
    Upsertable: true
    IgnoredProperties:
      - allowExternalSenders
      - assignedLabels
      - assignedLicenses
      - autoSubscribeNewMembers
      - hasMembersWithLicenseErrors
      - hideFromAddressLists
      - hideFromOutlookClients
      - isArchived
      - isSubscribedByMail
      - licenseProcessingState
      - unseenCount
    NavigationProperty:
      - members
      - owners
    RequiredOnWrite:
      - displayName
      - mailEnabled
      - mailNickname
      - securityEnabled
      - uniqueName
    ReadOnly:
      - createdDateTime
      - expirationDateTime
      - mail
      - onPremisesDomainName
      - onPremisesLastSyncDateTime
      - onPremisesNetBiosName
      - onPremisesSamAccountName
      - onPremisesSecurityIdentifier
      - onPremisesSyncEnabled
      - proxyAddresses
      - renewedDateTime
  - Name: microsoft.graph.application
    RootUri: /applications
    Upsertable: true
    RequiredOnWrite:
      - displayName
      - uniqueName
    ReadOnly:
      - appId
      - applicationTemplateId
      - certification
      - createdDateTime
      - publisherDomain
  - Name: microsoft.graph.servicePrincipal
    RootUri: /servicePrincipals
    Upsertable: true
    RequiredOnWrite:
      - appId
    ReadOnly:
      - applicationTemplateId
      - resourceSpecificApplicationPermissions
      - signInAudience
  - Name: microsoft.graph.federatedIdentityCredential
    RootUri: /applications/federatedIdentityCredentials
    Upsertable: true
    ContainerEntitySet: applications
    RequiredOnWrite:
      - audiences
      - issuer
      - name
      - subject
  - Name: microsoft.graph.oAuth2PermissionGrant
    RootUri: /oauth2PermissionGrants
    Upsertable: false
    Updatable: true
    RequiredOnWrite:
      - clientId
      - consentType
      - resourceId
    FilterProperty:
      - clientId
      - consentType
      - resourceId
    CompositeKey:
      - clientId
      - consentType
      - resourceId
  - Name: microsoft.graph.appRoleAssignment
    RootUri: /appRoleAssignedTo
    Upsertable: false
    Updatable: false
    ContainerEntitySet: servicePrincipals
    ContainerKeyProperty: resourceId
    RequiredOnWrite:
      - appRoleId
      - principalId
      - resourceId
    ReadOnly:
      - createdDateTime
      - principalDisplayName
      - principalType
    FilterProperty:
      - resourceId
    CompositeKey:
      - appRoleId
      - resourceId
  - Name: microsoft.graph.appRole
    ReadOnly:
      - origin
  - Name: microsoft.graph.informationalUrl
    ReadOnly:
      - logoUrl
  - Name: microsoft.graph.passwordCredential
    IgnoredProperties:
      - customKeyIdentifier
    ReadOnly:
      - hint
      - secretText
  - Name: microsoft.graph.permissionScope
    IgnoredProperties:
      - origin
  - Name: microsoft.graph.directoryObject
    ReadOnly:
      - deletedDateTime
  - Name: microsoft.graph.entity
    ReadOnly:
      - id
