# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# Create a production build artifact from the HEAD of the master branch.
trigger: none
pr: none

pool:
  name: Azure Pipelines
  vmImage: windows-latest
  demands:
    - msbuild
    - vstest

variables:
  - template: ./common-variables.yml

stages:
  - stage: build
    jobs:
      - job: build
        steps:
          - template: ./common-templates/install-tools.yml

          - template: ./common-templates/security-pre-checks.yml

          - template: ./common-templates/common-steps.yml
            parameters:
              Official: true

          - template: ./common-templates/security-post-checks.yml

  - stage: deploy
    condition: and(contains(variables['build.sourceBranch'], 'refs/heads/main'), succeeded())
    dependsOn: build
    jobs:
      - deployment: deploy
        environment: microsoftgraph-bicep-nuget-org
        strategy:
          runOnce:
            deploy:
              pool:
                vmImage: ubuntu-latest
              steps:
                - task: DownloadPipelineArtifact@2
                  displayName: Download nupkg from artifacts
                  inputs:
                    artifact: Nugets
                    source: current
                - task: NuGetCommand@2
                  displayName: "NuGet push"
                  inputs:
                    command: push
                    packagesToPush: "$(Pipeline.Workspace)/Nugets/Microsoft.Graph.Bicep.Types.*.nupkg"
                    nuGetFeedType: external
                    publishFeedCredentials: "microsoftgraph NuGet connection"
